name: Twitter Auto Poster Bot

on:
  schedule:
    # Peak engagement times (UTC):
    - cron: "0 12 * * *"  # 12 PM UTC (8 AM ET / 5 AM PT) - Morning peak
    - cron: "0 17 * * *"  # 5 PM UTC (1 PM ET / 10 AM PT) - Lunch peak  
    - cron: "0 21 * * *"  # 9 PM UTC (5 PM ET / 2 PM PT) - Evening peak
    - cron: "0 2 * * *"   # 2 AM UTC (10 PM ET / 7 PM PT) - Night peak
  workflow_dispatch: # Allow manual trigger

jobs:
  post-tweet:
    runs-on: ubuntu-latest
    environment: twitter-bot

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Run Twitter Bot
        env:
          APP_KEY: ${{ secrets.APP_KEY }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node index.js
